/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstitutionalDnaRouteImport } from './routes/institutional-dna'
import { Route as VolunteerRouteImport } from './routes/Volunteer'
import { Route as VisionRouteImport } from './routes/Vision'
import { Route as UpcomingProjectsRouteImport } from './routes/UpcomingProjects'
import { Route as TermsAndConditionsRouteImport } from './routes/TermsAndConditions'
import { Route as TeamRouteImport } from './routes/Team'
import { Route as SkillProgramsRouteImport } from './routes/SkillPrograms'
import { Route as RegistrationDetailsRouteImport } from './routes/RegistrationDetails'
import { Route as PrivacyPolicyRouteImport } from './routes/PrivacyPolicy'
import { Route as PartnerWithUsRouteImport } from './routes/PartnerWithUs'
import { Route as ObjectivesRouteImport } from './routes/Objectives'
import { Route as MissionRouteImport } from './routes/Mission'
import { Route as MemorandumAndRulesRouteImport } from './routes/MemorandumAndRules'
import { Route as MembersRouteImport } from './routes/Members'
import { Route as MediaRouteImport } from './routes/Media'
import { Route as LegalPoliciesRouteImport } from './routes/LegalPolicies'
import { Route as LearningHubRouteImport } from './routes/LearningHub'
import { Route as JourneyRouteImport } from './routes/Journey'
import { Route as ImpactRouteImport } from './routes/Impact'
import { Route as DonateAndSupportRouteImport } from './routes/DonateAndSupport'
import { Route as DonateRouteImport } from './routes/Donate'
import { Route as CookiePolicyRouteImport } from './routes/CookiePolicy'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as CampaignRouteImport } from './routes/Campaign'
import { Route as CSRPartnershipRouteImport } from './routes/CSRPartnership'
import { Route as BlogRouteImport } from './routes/Blog'
import { Route as AboutRouteImport } from './routes/About'
import { Route as IndexRouteImport } from './routes/index'

const InstitutionalDnaRoute = InstitutionalDnaRouteImport.update({
  id: '/institutional-dna',
  path: '/institutional-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/Volunteer',
  path: '/Volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/Vision',
  path: '/Vision',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingProjectsRoute = UpcomingProjectsRouteImport.update({
  id: '/UpcomingProjects',
  path: '/UpcomingProjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/TermsAndConditions',
  path: '/TermsAndConditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/Team',
  path: '/Team',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillProgramsRoute = SkillProgramsRouteImport.update({
  id: '/SkillPrograms',
  path: '/SkillPrograms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationDetailsRoute = RegistrationDetailsRouteImport.update({
  id: '/RegistrationDetails',
  path: '/RegistrationDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/PrivacyPolicy',
  path: '/PrivacyPolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/PartnerWithUs',
  path: '/PartnerWithUs',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/Objectives',
  path: '/Objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/Mission',
  path: '/Mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorandumAndRulesRoute = MemorandumAndRulesRouteImport.update({
  id: '/MemorandumAndRules',
  path: '/MemorandumAndRules',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/Members',
  path: '/Members',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/Media',
  path: '/Media',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPoliciesRoute = LegalPoliciesRouteImport.update({
  id: '/LegalPolicies',
  path: '/LegalPolicies',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubRoute = LearningHubRouteImport.update({
  id: '/LearningHub',
  path: '/LearningHub',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/Journey',
  path: '/Journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/Impact',
  path: '/Impact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateAndSupportRoute = DonateAndSupportRouteImport.update({
  id: '/DonateAndSupport',
  path: '/DonateAndSupport',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/Donate',
  path: '/Donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/CookiePolicy',
  path: '/CookiePolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/Campaign',
  path: '/Campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CSRPartnershipRoute = CSRPartnershipRouteImport.update({
  id: '/CSRPartnership',
  path: '/CSRPartnership',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/Blog',
  path: '/Blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Blog': typeof BlogRoute
  '/CSRPartnership': typeof CSRPartnershipRoute
  '/Campaign': typeof CampaignRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/Impact': typeof ImpactRoute
  '/Journey': typeof JourneyRoute
  '/LearningHub': typeof LearningHubRoute
  '/LegalPolicies': typeof LegalPoliciesRoute
  '/Media': typeof MediaRoute
  '/Members': typeof MembersRoute
  '/MemorandumAndRules': typeof MemorandumAndRulesRoute
  '/Mission': typeof MissionRoute
  '/Objectives': typeof ObjectivesRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/RegistrationDetails': typeof RegistrationDetailsRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/Team': typeof TeamRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/Vision': typeof VisionRoute
  '/Volunteer': typeof VolunteerRoute
  '/institutional-dna': typeof InstitutionalDnaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Blog': typeof BlogRoute
  '/CSRPartnership': typeof CSRPartnershipRoute
  '/Campaign': typeof CampaignRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/Impact': typeof ImpactRoute
  '/Journey': typeof JourneyRoute
  '/LearningHub': typeof LearningHubRoute
  '/LegalPolicies': typeof LegalPoliciesRoute
  '/Media': typeof MediaRoute
  '/Members': typeof MembersRoute
  '/MemorandumAndRules': typeof MemorandumAndRulesRoute
  '/Mission': typeof MissionRoute
  '/Objectives': typeof ObjectivesRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/RegistrationDetails': typeof RegistrationDetailsRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/Team': typeof TeamRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/Vision': typeof VisionRoute
  '/Volunteer': typeof VolunteerRoute
  '/institutional-dna': typeof InstitutionalDnaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Blog': typeof BlogRoute
  '/CSRPartnership': typeof CSRPartnershipRoute
  '/Campaign': typeof CampaignRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/Impact': typeof ImpactRoute
  '/Journey': typeof JourneyRoute
  '/LearningHub': typeof LearningHubRoute
  '/LegalPolicies': typeof LegalPoliciesRoute
  '/Media': typeof MediaRoute
  '/Members': typeof MembersRoute
  '/MemorandumAndRules': typeof MemorandumAndRulesRoute
  '/Mission': typeof MissionRoute
  '/Objectives': typeof ObjectivesRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/RegistrationDetails': typeof RegistrationDetailsRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/Team': typeof TeamRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/Vision': typeof VisionRoute
  '/Volunteer': typeof VolunteerRoute
  '/institutional-dna': typeof InstitutionalDnaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/About'
    | '/Blog'
    | '/CSRPartnership'
    | '/Campaign'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/Impact'
    | '/Journey'
    | '/LearningHub'
    | '/LegalPolicies'
    | '/Media'
    | '/Members'
    | '/MemorandumAndRules'
    | '/Mission'
    | '/Objectives'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/RegistrationDetails'
    | '/SkillPrograms'
    | '/Team'
    | '/TermsAndConditions'
    | '/UpcomingProjects'
    | '/Vision'
    | '/Volunteer'
    | '/institutional-dna'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/About'
    | '/Blog'
    | '/CSRPartnership'
    | '/Campaign'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/Impact'
    | '/Journey'
    | '/LearningHub'
    | '/LegalPolicies'
    | '/Media'
    | '/Members'
    | '/MemorandumAndRules'
    | '/Mission'
    | '/Objectives'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/RegistrationDetails'
    | '/SkillPrograms'
    | '/Team'
    | '/TermsAndConditions'
    | '/UpcomingProjects'
    | '/Vision'
    | '/Volunteer'
    | '/institutional-dna'
  id:
    | '__root__'
    | '/'
    | '/About'
    | '/Blog'
    | '/CSRPartnership'
    | '/Campaign'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/Impact'
    | '/Journey'
    | '/LearningHub'
    | '/LegalPolicies'
    | '/Media'
    | '/Members'
    | '/MemorandumAndRules'
    | '/Mission'
    | '/Objectives'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/RegistrationDetails'
    | '/SkillPrograms'
    | '/Team'
    | '/TermsAndConditions'
    | '/UpcomingProjects'
    | '/Vision'
    | '/Volunteer'
    | '/institutional-dna'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CSRPartnershipRoute: typeof CSRPartnershipRoute
  CampaignRoute: typeof CampaignRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DonateRoute: typeof DonateRoute
  DonateAndSupportRoute: typeof DonateAndSupportRoute
  ImpactRoute: typeof ImpactRoute
  JourneyRoute: typeof JourneyRoute
  LearningHubRoute: typeof LearningHubRoute
  LegalPoliciesRoute: typeof LegalPoliciesRoute
  MediaRoute: typeof MediaRoute
  MembersRoute: typeof MembersRoute
  MemorandumAndRulesRoute: typeof MemorandumAndRulesRoute
  MissionRoute: typeof MissionRoute
  ObjectivesRoute: typeof ObjectivesRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegistrationDetailsRoute: typeof RegistrationDetailsRoute
  SkillProgramsRoute: typeof SkillProgramsRoute
  TeamRoute: typeof TeamRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UpcomingProjectsRoute: typeof UpcomingProjectsRoute
  VisionRoute: typeof VisionRoute
  VolunteerRoute: typeof VolunteerRoute
  InstitutionalDnaRoute: typeof InstitutionalDnaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/institutional-dna': {
      id: '/institutional-dna'
      path: '/institutional-dna'
      fullPath: '/institutional-dna'
      preLoaderRoute: typeof InstitutionalDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Volunteer': {
      id: '/Volunteer'
      path: '/Volunteer'
      fullPath: '/Volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Vision': {
      id: '/Vision'
      path: '/Vision'
      fullPath: '/Vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UpcomingProjects': {
      id: '/UpcomingProjects'
      path: '/UpcomingProjects'
      fullPath: '/UpcomingProjects'
      preLoaderRoute: typeof UpcomingProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TermsAndConditions': {
      id: '/TermsAndConditions'
      path: '/TermsAndConditions'
      fullPath: '/TermsAndConditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Team': {
      id: '/Team'
      path: '/Team'
      fullPath: '/Team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SkillPrograms': {
      id: '/SkillPrograms'
      path: '/SkillPrograms'
      fullPath: '/SkillPrograms'
      preLoaderRoute: typeof SkillProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrationDetails': {
      id: '/RegistrationDetails'
      path: '/RegistrationDetails'
      fullPath: '/RegistrationDetails'
      preLoaderRoute: typeof RegistrationDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PrivacyPolicy': {
      id: '/PrivacyPolicy'
      path: '/PrivacyPolicy'
      fullPath: '/PrivacyPolicy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PartnerWithUs': {
      id: '/PartnerWithUs'
      path: '/PartnerWithUs'
      fullPath: '/PartnerWithUs'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Objectives': {
      id: '/Objectives'
      path: '/Objectives'
      fullPath: '/Objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mission': {
      id: '/Mission'
      path: '/Mission'
      fullPath: '/Mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MemorandumAndRules': {
      id: '/MemorandumAndRules'
      path: '/MemorandumAndRules'
      fullPath: '/MemorandumAndRules'
      preLoaderRoute: typeof MemorandumAndRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Members': {
      id: '/Members'
      path: '/Members'
      fullPath: '/Members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Media': {
      id: '/Media'
      path: '/Media'
      fullPath: '/Media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LegalPolicies': {
      id: '/LegalPolicies'
      path: '/LegalPolicies'
      fullPath: '/LegalPolicies'
      preLoaderRoute: typeof LegalPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LearningHub': {
      id: '/LearningHub'
      path: '/LearningHub'
      fullPath: '/LearningHub'
      preLoaderRoute: typeof LearningHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Journey': {
      id: '/Journey'
      path: '/Journey'
      fullPath: '/Journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Impact': {
      id: '/Impact'
      path: '/Impact'
      fullPath: '/Impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DonateAndSupport': {
      id: '/DonateAndSupport'
      path: '/DonateAndSupport'
      fullPath: '/DonateAndSupport'
      preLoaderRoute: typeof DonateAndSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Donate': {
      id: '/Donate'
      path: '/Donate'
      fullPath: '/Donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CookiePolicy': {
      id: '/CookiePolicy'
      path: '/CookiePolicy'
      fullPath: '/CookiePolicy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Campaign': {
      id: '/Campaign'
      path: '/Campaign'
      fullPath: '/Campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CSRPartnership': {
      id: '/CSRPartnership'
      path: '/CSRPartnership'
      fullPath: '/CSRPartnership'
      preLoaderRoute: typeof CSRPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Blog': {
      id: '/Blog'
      path: '/Blog'
      fullPath: '/Blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CSRPartnershipRoute: CSRPartnershipRoute,
  CampaignRoute: CampaignRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DonateRoute: DonateRoute,
  DonateAndSupportRoute: DonateAndSupportRoute,
  ImpactRoute: ImpactRoute,
  JourneyRoute: JourneyRoute,
  LearningHubRoute: LearningHubRoute,
  LegalPoliciesRoute: LegalPoliciesRoute,
  MediaRoute: MediaRoute,
  MembersRoute: MembersRoute,
  MemorandumAndRulesRoute: MemorandumAndRulesRoute,
  MissionRoute: MissionRoute,
  ObjectivesRoute: ObjectivesRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegistrationDetailsRoute: RegistrationDetailsRoute,
  SkillProgramsRoute: SkillProgramsRoute,
  TeamRoute: TeamRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UpcomingProjectsRoute: UpcomingProjectsRoute,
  VisionRoute: VisionRoute,
  VolunteerRoute: VolunteerRoute,
  InstitutionalDnaRoute: InstitutionalDnaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
